server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 30 dakika
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        same-site: none
        domain: localhost
        path: /
        max-age: 1800

spring:
  application:
    name: finance
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=finance;encrypt=true;trustServerCertificate=true
    username: zuhreb
    password: zuhre060.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show-sql: true
        format_sql: true

# JWT Configuration (ileride kullanmak için)
jwt:
  secret: 7I1TIewZ+keHBdh5eUnsOdMgFdMykcOHvSFE++0Cc6Y=
  expiration: 3600000

# WebSocket Configuration
ws:
  endpoint: /ws
  allowed-origins: "http://localhost:5173"

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001,http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

gemini:
  api:
    key: AIzaSyB0lYA0y6qqb1n9FmiYjLqu_nemfOSY7TU
  project:
    id: 377322490198
  location: us-central1
  model:
    name: gemini-2.5-flash-latest