server:
  port: 8080
spring:
  application:
    name: finance
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=finance;encrypt=true;trustServerCertificate=true
    username: zuhreb
    password: zuhre060.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show-sql: true

jwt:
  secret: 7I1TIewZ+keHBdh5eUnsOdMgFdMykcOHvSFE++0Cc6Y=
  expiration: 3600000

ws:
  endpoint: /ws
  allowed-origins: "http://localhost:5173"